### ISSUE TITLE
Watanabe's WAIC in python?

### ISSUE THREAD

**Issue by carlkl** [stan-dev/pystan#157]
Just curious: is the widely applicable information criterium WAIC available as a Python implemenation?

**Comment by andrewgelman** [comment]
HI, Aki and Jonah and I have a new paper on this which we will be posting very soon.  It’s not in pystan but it’s in Stan with R code.  It shoudl not be hard to put it into official Rstan and Pystan.
A

**Comment by carlkl** [comment]
thank you very much for this information.

**Comment by nigeljyng** [comment]
Sorry for replying in this closed thread, but has there been any work on this? Would love to have a WAIC function for pystan

**Comment by carlkl** [comment]
PSIS-LOO and AFAIK WAIC are now included in pymc3

**Comment by avehtari** [comment]
There's PSIS-LOO Python code here https://github.com/avehtari/PSIS
And discussion of making PyPi loo package here https://github.com/stan-dev/pystan/issues/278
Although PSIS-LOO is recommended instead of WAIC (http://arxiv.org/abs/1507.04544), WAIC function could be included in such package in a same way as it is included in CRAN loo package.
