### ISSUE TITLE
RFC: Pandas, xray integration

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#168]
Pandas seems very well established in the Python ecosystem. I wonder if at this point it might be useful to return Pandas dataframes from `extract` (or similar). Basically anywhere R returns a data.frame, Python might return a Pandas DataFrame.

Occasioned by watching SciPy 2015 talks, e.g., https://www.youtube.com/watch?v=5GlNDD7qbP4

**Comment by bob-carpenter** [comment]
All else being equal, fewer dependencies on other packages are better because there's then less to go wrong when they change, fewer license dependencies, and fewer things for users to learn (assuming the use of Pandas isn't transparent).

What would be the advantage to returning Pandas data structures?  And would it be possible to use a simpler built-in data structure that could be converted to Pandas for other processing?

**Comment by ariddell** [comment]
I'm inclined to agree. Using pandas is the only way to get feature parity with R's data.frame. Well, if people keep requesting it I guess we can revisit it.
