### ISSUE TITLE
pystan 2.7.0 on Anaconda?

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/pystan#169]
Are there any plans to make pystan 2.7.0 available through Anaconda for linux / mac os x?

**Comment by ariddell** [comment]
Nope. Should there be? 

I do want to make binary wheels available for Windows and Mac OS X via pypi eventually. The OS X wheels for this version aren't building fast enough to generate wheels via travis-ci as I have in the past. I need to figure out a solution there. I'm hesitating about taking the plunge and learning how to do this in Jenkins.

**Comment by tobeplugged** [comment]
I second that request. Anaconda has proven to be invaluable for any precompiled packages in python.
Even though pystan usually compiles very well it would be nice to quickly be able to install it via conda.

I've started to produce a conda recipe for pystan, but came across #171.

**Comment by ariddell** [comment]
@tobeplugged Can you modify requirements.txt to use Cython<0.23 and then build it?

OK -- so the problem right now with OS X wheels is that travis-ci is timing out on me. (https://travis-ci.org/ariddell/pystan-wheel-builder).

I'll take a stab at building the wheels by hand tonight.

**Comment by tobeplugged** [comment]
I can, no worries.
I will open a pull request for the added conda recipe as soon as I have it working right. Might take a few days though.

Re the wheels, as far as I gather, it would also be possible to use travis to build and upload conda packages. Might be worth a look.

**Comment by tobeplugged** [comment]
Sorry, I was a little quick with my answer, one test still fails: `pystan.tests.test_rstan_stanfit.TestStanfit`

The reason (I think) is that `np.testing.assert_equal` will fail the two arguments are note __exactly__ the same. This is trouble if the arguments are floats due to very small rounding errors, you should probably use 'np.testing.asser_allmost_equal' with a reasonably low error bound to avoid future troubles.

**Comment by ariddell** [comment]
@tobeplugged can you submit a PR for the assert_almost_equal? That would be very welcome.

Didn't get around to building the wheels last night.

Not sure what benefit there is in having both OS X binary wheels on PyPI and conda binary wheels. Clearly with linux there's a benefit since you can't have binary wheels on PyPI (yet?) but can on conda.

**Comment by tobeplugged** [comment]
Having a conda package is mainly a matter of convenience I guess. Anaconda has quite a wide user base and is very als easy to install and use making it nice for teaching.

**Comment by ariddell** [comment]
Ok, I got the OS X wheels building. Now the problem is that the size is exceeding the PyPI wheel file size limit. Making a request to increase pystan's limit.

**Comment by ariddell** [comment]
Binary wheels are up on PyPI. If you run into problems, please open a new issue.
