### ISSUE TITLE
HI from Stan meetup on Sat in NYC!! 

### ISSUE THREAD

**Issue by SlyOne** [stan-dev/pystan#198]
So, feel to ignore......

Working through Stan at this meetup. It would be really helpful if there was 
an example in Stan which showed its features.  

My thought was to take titanic data sets.... Show analysis of it in statsmodels, 
scikit learn and also in stan for logistic regression as a blog post. 

This would be helpful to compare the different modules available and highlight 
unique value each model brings to python.

**Comment by ariddell** [comment]
An analysis of the titanic dataset sounds like a great pedagogical example. Good luck!

**Comment by bob-carpenter** [comment]
This isn't a pystan issue, so I'm closing this.  If you want to contribute an example, it should go in the stan-dev/example-models repo.  You can look there for many examples as well as our manual.

**Comment by jgabry** [comment]
This isn't an "issue" per se but I think the intent was pystan-specific in
that a lot of the statistical analysis packages for Python have an example
using the titanic data and so it'd be nice to have one for pystan too for
prospective users.

**Comment by bob-carpenter** [comment]
OK, I didn't realize it was the norm in Python.  Even so, examples should go in example-models.  

Maybe there's a doc issue for PyStan after the example model gets built.

Also, please use titles for issues that describe the issue.  Otherwise, we can't make sense of the list of outstanding issues.

Thanks!
