### ISSUE TITLE
Cache results of fit summary

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#203]
Printing a fit object (i.e. generating the human-readable table of summary statistics) is computationally intensive. The result should be cached (at some level).

This memoize decorator looks rather good: https://github.com/JohnReid/Cookbook/blob/master/python/cookbook/cache_decorator.py

**Comment by bob-carpenter** [comment]
Are you thinking about caching the values or the
printed string?  

If you want to use that code, you need to make sure the
PSF license (I'm not familiar with it) is compatible with
the GPL license you chose for PyStan.

I don't understand Python well enough to comment on the
code, but the issues with caches are usually

 * how they get flushed and/or updated when values should change,

 * how they are synchronized for multiple thread access (and again, 
   I don't know enough about Python to know if that's an issue), and 

 * how much overhead they induce on the initial call and how
   much memory they use.  

Very sophisticated caches will be memory controlled, so you
use something like like a least-recently-used auto-flush to
make sure you bound the memory (that's what I did in all of
our NLP product code, because of the long tail of natural
language --- if you just keep caching, memory will explode).

- Bob

**Comment by ariddell** [comment]
I did notice the PSF license. What would be cached would be the summary statistics derived from the chains. I think the contents of the chains are immutable at this point. I believe RStan already caches the calculation as well.

**Comment by stephen-hoover** [comment]
The Python standard library has a memoizing decorator: https://docs.python.org/3/library/functools.html#functools.lru_cache . I don't think it's in the Python 2 standard library, though.

**Comment by ariddell** [comment]
Let's use that. The decorator could be a noop for Python 2.

**Comment by ariddell** [comment]
PyStan 3 has this.
