### ISSUE TITLE
UTF-8 program code should be passed to Stan

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#223]
PyStan will fail if there are non-ascii characters anywhere in Stan program code but UTF-8 should be allowed in comments.

**Comment by ahartikainen** [comment]
Add `'ignore'` to pystan/api.py:stanc function. Is this too error-prone?

    model_code_bytes = model_code.encode('ascii')

to

    model_code_bytes = model_code.encode('ascii', 'ignore')
    
Are comments removed from the cpp code? If they are, this should work.

**Comment by bob-carpenter** [comment]
If you have UTF-8 in comments, it should be OK as far as the underlying Stan code is concerned.  It should even be OK in code, but all the rest of the I/O isn't UTF-8, so it probably won't render.  

It's not quite that we remove the comments, but rather that the parser treats them as whitespace.

**Comment by ahartikainen** [comment]
Some testing.

    model_code = """
    data {
      // line comment with äöå
      /* multiline --- äöå
          comment ---  äöå */
      
      int N;
      }
     """

And as a string this is

    '\ndata {\n  // line comment with äöå\n  /* multiline --- äöå\n     comment --- äöå */\n  \n  int N;\n  }\n'

Encoding examples
    model_code.encode('ascii')
    # UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-33: ordinal not in range(128)

    model_code.encode('ascii', 'ignore')
    # b'\ndata {\n  // line comment with \n  /* multiline --- \n     comment ---  */\n  \n  int N;\n  }\n'

    model_code.encode('uft-8')
    # b'\ndata {\n  // line comment with \xc3\xa4\xc3\xb6\xc3\xa5\n  /* multiline --- \xc3\xa4\xc3\xb6\xc3\xa5\n     comment --- \xc3\xa4\xc3\xb6\xc3\xa5 */\n  \n  int N;\n  }\n'

What if comments are removed in python before encoding?

    import re
    
    # these lines match only comments
    # re_multiline = r'\/\*[\s\S]*\*\/'
    # re_oneline = r'\/\/[\s\S].*'

    # match everything between /* and */ and remove whitespace before and after (including newline)
    re_multiline = r'\s*\/\*[\s\S]*\*\/\s*'
    # match everything after // and remove whitespace before and after (including newline)
    re_oneline = r'\s*\/\/[\s\S].*\s*'
    
    re_comments = "{}|{}".format(re_multiline, re_oneline)

    re.sub(re_comments, "", model_code)
    # '\ndata {int N;\n  }\n'

**Comment by bob-carpenter** [comment]
Thanks for the Python-level tests.  

I was talking about Stan itself at the C++ level.  There isn't any character processing, just straight up byte-level processing.  The identifiers are restricted to ASCII primarily because the grammar says something like `a-zA-Z0-9_` for the set of allowable characters.  That would be easy to change, but we thought it'd be too error prone to have people having to deal with encodings in Stan programs.

I'm curious how that works for Julia.

**Comment by ariddell** [comment]
I just hit this. I had a comment referring to a work by "Schöwerling".

Let's just use ``model_code.encode('ascii', 'replace')`` for now? @ahartikainen would you like to submit a PR?

**Comment by ahartikainen** [comment]
#304

**Comment by ahartikainen** [comment]
I made PR #304 

There is a mention of possible problem with ternary operator.

    for (n in aöb:c)

to

    for (n in a?b:c)

If utf-8 characters are in program code outside comments, Stan probably fails to compile it and raises error, but there is no link to utf-8 and replace.

Will pystan fail if we just use

    model_code.encode('utf-8')

Then utf-8 characters will raise correct error in Stan (?)

**Comment by bob-carpenter** [comment]
What is the goal here?  Is it to catch errors in encodings?

UTF-8 is the identity operator for ASCII characters (the first 128 code points overlap).  And it never uses any of the ASCII characters otherwise.  So there's no way to accidentally read a UTF-8 byte as an ASCII byte if it's not meant to be that ASCII byte.  See:

https://en.wikipedia.org/wiki/UTF-8#Description

So as long as UTF-8 is only in comments, it should be fine.

The only danger in using it outside of comments is that it won't render properly or match things like dictionaries in Python or lists in R.
