### ISSUE TITLE
Multiple chains with multicore sometimes running in series, not parallel.

### ISSUE THREAD

**Issue by jeffalstott** [stan-dev/pystan#228]
#### Summary:

pystan supports multicore by default, so that when sampling with multiple chains each chain gets a different core.  One would think that this means the chains are running in parallel, but that doesn't appear to always be the case.
#### Description:

I have observed that using pystan on a single computer to run multiple chains across several cores is slower than using cmdstan to run multiple chains as entirely separate processes (maybe even separate computers). I haven't inspected the difference between pystan and cmdstan closely, so I'm still not sure if that's true. But it would be true if pystan isn't actually running multiple chains in parallel, but just doing pieces of each chain in series. `htop` tells me that if I run 4 `sampling` with `chains=4`, 4 cores do indeed start crunching at 100%. But today I finally caught pystan giving output that was clearly calculating in series:
#### Steps and Output

```
n_chains = 4
n_iter = 600
stan_data = {...}
my_pstan_model.sampling(data=stan_data, chains=n_chains, iter=n_iter)
```

And this is the stdout:

```
Chain 3, Iteration:   1 / 600 [  0%]  (Warmup)
Chain 2, Iteration:   1 / 600 [  0%]  (Warmup)
Chain 1, Iteration:   1 / 600 [  0%]  (Warmup)
Chain 0, Iteration:   1 / 600 [  0%]  (Warmup)
Chain 2, Iteration:  60 / 600 [ 10%]  (Warmup)
Chain 0, Iteration:  60 / 600 [ 10%]  (Warmup)
Chain 3, Iteration:  60 / 600 [ 10%]  (Warmup)
Chain 2, Iteration: 120 / 600 [ 20%]  (Warmup)
Chain 2, Iteration: 180 / 600 [ 30%]  (Warmup)
Chain 2, Iteration: 240 / 600 [ 40%]  (Warmup)
Chain 2, Iteration: 300 / 600 [ 50%]  (Warmup)
Chain 2, Iteration: 301 / 600 [ 50%]  (Sampling)
Chain 2, Iteration: 360 / 600 [ 60%]  (Sampling)
Chain 2, Iteration: 420 / 600 [ 70%]  (Sampling)
Chain 2, Iteration: 480 / 600 [ 80%]  (Sampling)
Chain 2, Iteration: 540 / 600 [ 90%]  (Sampling)
Chain 2, Iteration: 600 / 600 [100%]  (Sampling)#
#  Elapsed Time: 4792.37 seconds (Warm-up)  
#                11866.7 seconds (Sampling)
#                16659.1 seconds (Total)
#

Chain 1, Iteration:  60 / 600 [ 10%]  (Warmup)  # Wat. 
```

After this only 3 cores are calculating at 100%; presumably the other core that was running chain 2 stopped.
#### Expected Output:

All chains to actually be running in parallel.
#### Possible cause of the problem

Memory management? Only a fraction of the RAM is actually used (2.6GB out of 64GB), so if the issue is the different chains are fighting for memory then it seems like there should be a fix available. 

Something else?
#### PyStan Version:

2.9.0.0
#### Python Version:

Python 3.4.3, Ipython 4.0.1
I'm calling this code within IPython, but NOT within an Ipython notebook (which I understand at least used to have some issues with multicore).
#### Operating System:

Linux something.

**Comment by ariddell** [comment]
PyStan's using multiple cores and independent copies of the input data. It's wastefully parallel right now. Sometimes the chains run at different speeds though as they do have different random initializations.

**Comment by bob-carpenter** [comment]
Do they appear to not run in parallel when they run
for longer than a fraction of a second?  There's a bit
of startup time per chain and at least in RStan, it
can appear they're not running in parallel.

**Comment by jeffalstott** [comment]
@bob-carpenter In the example I gave above, the chains are running for hours. I don't know that I've ever done anything in stan that took less than a minute. 

@ariddell the first chain (which appears to run first) takes over 4.5 hours before the other chains seem to get addressed. (The other chains are still running). Does it seem plausible that chains could have such differences in their runtimes? If so, then I guess that's that. I find it surprising, but I'm not an expert. (This would still not address why Pystan is running far slower than cmdstan, but it may be related to the fact that cmdstan is not actually fitting successfully, as I mentioned [elsewhere](https://github.com/stan-dev/pystan/issues/226#event-682859671) and intended to deal with separately)

**Comment by bob-carpenter** [comment]
The underlying sampling algorithms run the same C++
code in CmdStan and PyStan.  There is some difference
between the initialization routines, but otherwise
they should supply the same results given the same seed,
chain ID, same initial values.

We're pulling more of the algorithmic work back into
the C++ really soon so that they'll be identical top-to-bottom.

- Bob

**Comment by ariddell** [comment]
Any more details? PyStan definitely should be running in parallel. This is, however, hard to test given our current resources since our testing environment only makes ~1 core available. In the future we could probably figure out a way to make sure that PyStan is sampling in parallel as expected.

**Comment by ariddell** [comment]
I can't reproduce this on linux. If someone else sees this please re-open.

**Comment by solarqiang** [comment]
I encountered the same problem recently.

I found sampling multiple chains are significantly slower than single chains, even when the number of chains are much smaller than cores of CPU available, and free RAM are abundant.
The time it takes for a single gradient evaluation is much higher when using 16 chains rather than a single chain, though it does occupy 16 cores over one core when doing so. The problem persists after left running overnight.

I'm using pystan 2.18.0, Python 3.6.5, Ubuntu 18.04.

I write a simple model to probe the problem.
```
data {
   int<lower=4> N; // Number of data points
   real x[N];      // the 1st predictor
   real y[N];      // the 2nd predictor
   real z[N];      // the outcome
}
parameters {
   real alpha;     // intercept
   real betax;     // x-slope
   real betay;     // y-slope
   real<lower=0> eps;       // dispersion
}
model {
   for (i in 1:N)
      z[i] ~ normal(alpha + betax * x[i] + betay * y[i], eps);
}
```

Then I used synthtetic data to test the model:
```python
from numpy import *
Nobs = 20
x_true = random.uniform(0,10, size=Nobs)
y_true = random.uniform(-1,1, size=Nobs)
alpha_true = 0.5
beta_x_true = 1.0
beta_y_true = 10.0
eps_true = 0.5
z_true = alpha_true + beta_x_true*x_true + beta_y_true*y_true
z_obs = z_true + random.normal(0, eps_true, size=Nobs)

data = {'N':Nobs, 'x':x_true, 'y':y_true, 'z':z_obs}
model = pystan.StanModel(model_code=model_code)

%timeit -r 5 model.sampling(data=data, chains=1, iter=1000, warmup=0)
%timeit -r 5 model.sampling(data=data, chains=16, iter=1000, warmup=0)
```

The results are as follows:
```
23.3 ms +- 506 us per loop (mean +- std. dev. of 5 runs, 10 loops each)
565 ms +- 7.03 ms per loop (mean +- std. dev. of 5 runs, 1 loop each)
```
I ran the test on two different machines with 16/32 cores with hyperthreading, 32G RAM, at low load.

I also tested it using different pystan versions. `2.17.1` and `2.17.0` gave smiliar results, and `2.16` does not complie the model for unknown reason. Interestingly, `2.15` gave a faster result than newer versions, though sampling multiple chains are still significantly slower than single chain:
```
8.08 ms +- 74.9 us per loop (mean +- std. dev. of 5 runs, 100 loops each)
393 ms +- 20.1 ms per loop (mean +- std. dev. of 5 runs, 1 loop each)
```

**Comment by bob-carpenter** [comment]
Thanks for the careful and reproducible report---it's very helpful for debugging.

Measuring what's going on in parallel is tricky as any of CPU speed, CPU cache, RAM, or disk can become bottlenecks.  As parallelization increases, so does contention.  For example, shared disk access on clusters is typically slow compared to built-in solid-state drives in a single computer.  As another example, if the program executes very quickly relative to the amount of output it produces, then disk access or RAM/cache access can become a bottleneck as the CPU races ahead of memory's ability to keep up.

My first suggestion is to measure what happens with 2, 4, and 8 chains and nothing else going on on the computer.

In your actual case, 16 parallel chains with 32GB RAM leaves 2GB/chain, which isn't a lot.  And the data sizes are very small, so the iterations should be very fast.  That means a lot of back-and-forth between CPU and disk.  So another thing to try would be scaling up the data sizes (so that amount of computation relative to number of parameters increases) to see what happens.

Speed of memory can also be a bottleneck---until very recently, memory was a good deal slower than CPUs.  The total amount of memory may not be a bottleneck here, but contention on the buses between CPU and memory can be a bottleneck, as can overall cache and per-CPU cache sizes.  Also, what kind of disk situation do you have for persistent memory (shared spinny disks, dedicated solid state drive(s), RAID configuration, etc.)?    

I'm not sure what Python does under the hood here for the number of chains---there may be overhead there that we don't see in bare OS calls from CmdStan or in RStan.

**Comment by solarqiang** [comment]
Thank you for your detailed explanation and suggestions. I followed your suggestion, using 20k samples,  running 10k iterations in 1, 2, 4, 8, 16 chains. The results are as follows.
```
32.4 s +- 106 ms per loop (mean +- std. dev. of 3 runs, 1 loop each)
33.4 s +- 360 ms per loop (mean +- std. dev. of 3 runs, 1 loop each)
33.8 s +- 283 ms per loop (mean +- std. dev. of 3 runs, 1 loop each)
1min 16s +- 21.7 s per loop (mean +- std. dev. of 3 runs, 1 loop each)
2min 41s +- 8.32 s per loop (mean +- std. dev. of 3 runs, 1 loop each)
```
Now I understand that there's nothing wrong with pystan in this regard and the hardware may bottleneck the performance on large and heavy load. I may consider optimizing the model or upgrade the hardware as a solution.
