### ISSUE TITLE
ADVI status of pystan

### ISSUE THREAD

**Issue by sachinruk** [stan-dev/pystan#238]
Hi,

Just checking if ADVI has been implemented in the latest version in the master branch? If so should I install from (i.e. is it stable?). Just saw a commit with ADVI in it, hence why I am asking. 

Lastly, is there any plans to support minibatches? pymc3 seems to be doing it already, so fingers crossed it will be available in pystan/ stan.

Cheers,
Sachin

**Comment by syclik** [comment]
@sachinruk, I'm closing this issue because it's not an issue. These sorts of things are better taken up on the [stan-users mailing list](https://groups.google.com/forum/?fromgroups#!forum/stan-users) rather than adding an issue that can't really be fixed.

Regarding ADVI on PyStan, I think the answer is yes, but I'd wait until Allen says it's ok.

Regarding minibatches: please ask on the mailing list, not through an issue.

Thanks.

**Comment by ariddell** [comment]
Hi @sachinruk , if you're comfortable experimenting you can try out ``vb()`` from the ``develop`` branch.
