### ISSUE TITLE
Could not find a version that satisfies the requirement httpstan<4.5,>=4.4

### ISSUE THREAD

**Issue by shloksobti** [stan-dev/pystan#292]
I'm running Ubuntu 18.04 of WSL2. Trying to install pystan leads to the following error:

Could not find a version that satisfies the requirement httpstan<4.5,>=4.4 (from pystan) (from versions: 0.1.0, 0.1.1, 0.2.3, 0.2.5, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.5, 0.7.6, 0.8.0, 0.9.0, 0.10.1, 1.0.0)                                                                                         No matching distribution found for httpstan<4.5,>=4.4 (from pystan)

**Comment by riddell-stan** [comment]
Can you use Ubuntu 20.04 under WSL2? Does such a thing exist?

It is possible to get things working under Ubuntu 18.04 but you do need to compile httpstan by yourself. Officially, Ubuntu 18.04 is not supported.

**Comment by riddell-stan** [comment]
Closing as PyPI wheels are not supported under Ubuntu 18.04. This lack of support is indicated in the documentation.

**Comment by hikmatyarhasan** [comment]
@riddell-stan  - I am using Ubuntu 20.04 under WSL2 and am getting the same error as @shloksobti when attempting to install pystan. I have gcc v9.3.0 installed too.

**Comment by riddell-stan** [comment]
I think I know what this issue is. Sorry for the mixup.

I think you need to upgrade pip first. The version of pip which ships with 20.04 is pretty old and doesn't know about newer wheel formats. So first run pip install -U pip. Then things should work fine on Ubuntu 20.04.

If this solves the problem for you on WSL2 we should certainly add this step to the installation instructions in the docs.

**Comment by riddell-stan** [comment]
FYI: You no longer need to upgrade pip on Ubuntu 20.04 for pystan to work.
