### ISSUE TITLE
neg_binomial_2_log_rng exception occurring in PyStan and not Cmdstan

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#297]
Reported by Nathan Sanders.

PyStan model in https://github.com/nesanders/massshootings (python code commented out) raises the following error.

```
ValueError: Exception thrown at line 100: neg_binomial_2_log_rng:
Random number that came from gamma distribution is 1.08116e+11, but
must be less than 1.07374e+09
```

**Comment by bob-carpenter** [comment]
This is a stan-dev/math issue, not a pystan issue.  Until we change the integer type to long, there's no way to deal with super-large RNGs.  We default to a continuous approximation then truncate to avoid some overflow, but this overflow can't be solved without a longer integer type in Stan.

Having said that, you can use a real value instead of an integer and use the gamma approximation directly to solve this problem.  Ideally as a  `neg_binomial_2_log_real_approx`;  we could even build some of these into Stan, but the better solution is to go to long integers.  That's a Stan issue as well as a math issue---both need to be updated.

**Comment by bob-carpenter** [comment]
Re-open as stan-dev/stan and stan-dev/math issues to deal with integer to long.

**Comment by ariddell** [comment]
@bob-carpenter I'm confused about the issue here. Why would it only occur in PyStan and not Cmdstan? Is cmdstan performing some conversion that pystan is not (and should)?

**Comment by josswright** [comment]
I just found this issue via a lucky Google whilst also playing with the Mass Shootings model and running into the same error. Is there a link to the current issues in stan-dev/stan and stan-dev/math? What's the status of this? 

More immediately, is there a good current solution/workaround to get the Mass Shootings code working as of now? Given that the StanCon2017 talk video and slides are there to support it, it comes across as a particularly useful worked example.

**Comment by riddell-stan** [comment]
Someone needs to open a bug report on this in stan-math. I don't think it has been fixed.

In any event, I found this bit of code which suggests a workaround:

```
def neg_binomial_2_rng(mu, phi):
    """Generate a sample from neg_binomial_2(mu, phi).

    This function is defined here in Python rather than in Stan because Stan
    reports overflow errors.

    $E(Y) = mu$
    $Var(Y) = mu + mu^2 / phi

    This function will work fine with arrays.

    """
    return np.random.poisson(np.random.gamma(phi, mu / phi))
```
