### ISSUE TITLE
Dir-Categorical model with empty data categories

### ISSUE THREAD

**Issue by scfrank** [stan-dev/pystan#310]
I'm observing some unusual behaviour with a simple Dirichlet-Categorical model
when it's given data that only has a subset of the categories represented
(i.e. theta is defined over K=6 categories, but the data only includes members
of categories 1-4). In this scenario, the last (theta[5]) category is
consistently assigned more probability mass than e.g. theta[4], even though
both categories have no data associated with them and the prior should be the
same.

A minimal example: 
[dircat.py.txt](https://github.com/stan-dev/pystan/files/821953/dircat.py.txt)

This outputs, for example -

    mean se_mean     sd   2.5%    25%    50%    75%  97.5%  n_eff Rhat
    theta[0]       0.34  5.5e-4   0.01   0.32   0.33   0.34   0.35 0.36  390.0   1.01
    theta[1]       0.31  4.1e-4 9.8e-3   0.29    0.3   0.31   0.32 0.33  567.0    1.0
    theta[2]       0.35  4.9e-4   0.01   0.32   0.34   0.35   0.35   0.37  470.0 1.0
    theta[3]     9.1e-7  3.9e-7 1.8e-51.5e-3012.2e-2121.9e-1221.6e-51 1.4e-8 2065.0 nan
    theta[4]     7.4e-7  3.4e-7 1.5e-51.7e-2971.1e-2072.5e-1283.0e-59 8.2e-8 1881.0 nan
    theta[5]     1.7e-5  2.2e-6 9.7e-51.3e-235.7e-152.0e-11 9.6e-8 2.0e-4 1874.0 nan

It looks (but I'm guessing here) that this might be some kind of
underflow/rounding error along with the last bin being assigned probability 1 -
sum(other categories).

In the minimal example (though not in the full model), Rhat is nan for the data-less categories. This might be related to https://github.com/stan-dev/pystan/issues/133?

**Comment by ahartikainen** [comment]
This might be a more of a problem with Stan than pystan? 

Nans on Rhats are done in python side.

**Comment by scfrank** [comment]
Sure - I wasn't sure whether it would fall under pystan, stan, or stan-math. Can you just move the issue or should I add it as a new issue in stan (or stan-math)?

**Comment by ariddell** [comment]
The n_eff is a bit low on some of the initial components -- I'd run the chain longer. If the problem still shows up, open an issue against Stan. Thanks for the report!

**Comment by bob-carpenter** [comment]
Thanks for the report and example.

In practice, you probably don't want to be using dirichlet(.005) as a prior as it drives your posterior estimates into arithmetically unstable regions:

>              mean se_mean     sd   2.5%    25%    50%    75%  97.5%  n_eff Rhat
> theta[4]     7.4e-7  3.4e-7 1.5e-51.7e-2971.1e-2072.5e-1283.0e-59 8.2e-8 1881.0 nan
> theta[5]     1.7e-5  2.2e-6 9.7e-51.3e-235.7e-152.0e-11 9.6e-8 2.0e-4 1874.0 nan

As you can see the 0.025 quantile is down at 10^(-200).  You're probably getting all kinds of divergence warnings (don't know how to find those in PyStan) about the instability warning you that you can't trust the answer.

Trying to do soft variable selection like this is going to produce priors that
are very sensitive to the posteriors. 

> It looks (but I'm guessing here) that this might be some kind of
> underflow/rounding error along with the last bin being assigned probability 1 -
> sum(other categories).

Indeed 1 - x is notoriously unstable for values of x near 1.

P.S.  Why are the numbers all run together?  It looks like an issue with PyStan output.

**Comment by scfrank** [comment]
Thanks for the fast and informative responses. I'm new to stan and it's
really helpful to see what I should be paying attention to.

On 7 March 2017 at 04:24, Bob Carpenter <notifications@github.com> wrote:

> Thanks for the report and example.
>
> In practice, you probably don't want to be using dirichlet(.005) as a
> prior as it drives your posterior estimates into arithmetically unstable
> regions:
> ...
> As you can see the 0.025 quantile is down at 10^(-200). You're probably
> getting all kinds of divergence warnings (don't know how to find those in
> PyStan) about the instability warning you that you can't trust the answer.
>

Yes - the model is fine with dirichlet(0.1); at dir(0.01) the instability
shows up. This is with iter=10000.

>
> Trying to do soft variable selection like this is going to produce priors
> that
> are very sensitive to the posteriors.
>

I don't follow?
I'm using tiny priors in a cognitive model in an attempt to match
regularising behaviour, i.e. where the most frequently seen category is
overrepresented in prediction. However there are some other issues with the
model as well as this one so I'm going to have to do some rethinking in
general. I thought this bug might be a separate issue but as so often it
turns out to all be interconnected.


> > It looks (but I'm guessing here) that this might be some kind of
> > underflow/rounding error along with the last bin being assigned
> probability 1 -
> > sum(other categories).
>
> Indeed 1 - x is notoriously unstable for values of x near 1.
>
> P.S. Why are the numbers all run together? It looks like an issue with
> PyStan output.
>
> This is just an accident of copy-paste from my vim where tabs turn into
spaces, sorry.

**Comment by bob-carpenter** [comment]
Not a bug, just hitting the limits of floating point.

**Comment by bob-carpenter** [comment]
Not really a bug so much as you're running up against the limits of double-precision floating-point calculations.

We'd rather have these discussions on our users group (linked under community on mc-stan.org).

More below.

> On Mar 7, 2017, at 6:02 AM, Stella Frank <notifications@github.com> wrote:
> 
> Thanks for the fast and informative responses. I'm new to stan and it's
> really helpful to see what I should be paying attention to.

This isn't a Stan issue so much as a stats issue.  

> Yes - the model is fine with dirichlet(0.1); at dir(0.01) the instability
> shows up. This is with iter=10000.

Not surprising.  You shouldn't need that many iterations in Stan.

> > Trying to do soft variable selection like this is going to produce priors
> > that
> > are very sensitive to the posteriors.
> >
> 
> I don't follow?

By setting the priors alpha[k] = 0.005, you are saying that you expect
the answers to be in the corners of the simplex.  Basically, you're
saying you expect one variable to be on and the others to be off.

Try simulating from a Dirichlet with that prior and look at the draws.
They'll look like (0, 0, ..., 1, ... 0).

I did it in RStan and here are the first 20 draws:


iterations   [,1]   [,2]   [,3]   [,4]   [,5]
      [1,]  5e-27  1e-21 2e-104  9e-29  1e+00
      [2,] 2e-131  4e-74  1e+00 4e-171  2e-79
      [3,] 2e-104 1e-108  1e+00  3e-04 3e-129
      [4,]  2e-10  1e+00 1e-106  3e-54 2e-101
      [5,]  3e-11 2e-155  1e+00  2e-09 5e-235
      [6,]  2e-05 6e-152  1e+00  3e-80 3e-137
      [7,]  1e-08  2e-85 5e-279  1e+00 4e-105
      [8,] 3e-112  1e-36  4e-20  1e+00  1e-47
      [9,]  1e-11  2e-26  1e-24  1e+00 2e-110
     [10,]  1e+00  3e-46  6e-80 2e-188  2e-18
     [11,]  1e+00  2e-30  3e-32  1e-50  3e-18
     [12,]  2e-41  1e+00  4e-19  1e-45 5e-157
     [13,]  9e-21  2e-40 2e-160  7e-40  1e+00
     [14,]  2e-39  1e+00  2e-69  2e-24  3e-02
     [15,]  4e-13  1e+00 5e-121  3e-04  6e-50
     [16,] 2e-137  6e-11  1e+00 5e-181  6e-33
     [17,]  2e-36 5e-268 2e-102  3e-43  1e+00
     [18,] 2e-110  4e-54 7e-143  1e+00  1e-24
     [19,] 3e-115  4e-17  1e+00  3e-64  0e+00
     [20,]  0e+00 3e-139  2e-19  5e-61  1e+00

You can see that draws from the prior have one value near 1 and the rest very
near zero.  I rounded down to one digit just to highlight the scale.

Is this what you expect the answers to look like?  If not, then it's
the wrong prior to use.  

You have three categories with values close to 0.3, which is nothing at
all like what you see in draws from the prior.

By prior sensitivity, I mean as you gradually raise this prior toward 1,
you'll see the draws become a uniform distribution over simplexes and as it
goes above 1, you'll see the probability mass concentrate around symmetric
answers (where all probabilities are equal).

> I'm using tiny priors in a cognitive model in an attempt to match
> regularising behaviour, i.e. where the most frequently seen category is
> overrepresented in prediction.

The small Dirichlet prior isn't going to do that---it's going to
have a posterior mean which is very close to the frequencies.

You can think of the Dirichlet prior as giving you the prior counts
in each category minus 1.  That's why when the parameter is all 1, it's
uniform --- no prior counts.

> However there are some other issues with the
> model as well as this one so I'm going to have to do some rethinking in
> general. I thought this bug might be a separate issue but as so often it
> turns out to all be interconnected.

It's an example of what Andrew calls the Folk Theorem:

http://andrewgelman.com/2008/05/13/the_folk_theore/

...

> > P.S. Why are the numbers all run together? It looks like an issue with
> > PyStan output.
> >
> > This is just an accident of copy-paste from my vim where tabs turn into
> spaces, sorry.

Glad to hear it's not a problem on our end!
