### ISSUE TITLE
Handling complex numbers

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan#340]
#### Describe the bug

Stan 2.28 supports complex data type. We should handle it correctly and add tests.

https://github.com/stan-dev/stan/pull/3056

**Comment by riddell-stan** [comment]
This might merit some discussion. I'm not sure how best to do this. (Here's one approach: <https://stackoverflow.com/a/24375113>)

How is CmdStan going to encode/decode complex numbers in json? Might be worth checking out their approach.

**Comment by WardBrian** [comment]
CmdStan for inputs treats a complex number as just a 2-long array. In json, it's something like

`"z": [1,2]`

This generalizes to arrays, so an `array[3] complex` type is represented as a 3x2 array. 

For output, the same behavior is more or less done, but the flattened column headers end with `.real` and `.imag` for this final index, rather than 0,1.


CmdStanPy's support can be seen in these two PRs:
https://github.com/stan-dev/cmdstanpy/pull/535
https://github.com/stan-dev/cmdstanpy/pull/537

**Comment by riddell-stan** [comment]
Thanks @WardBrian . This is useful.

Since cmdstanpy and cmdstan support complex numbers, there isn't an enormous amount of urgency to support it in pystan.

Also, I think we should be free to explore other options. Maybe it makes sense to finally move to a serialization format which actually supports differentiating between float, int, and complex. Protobuf and graphql seem like they would both work better than JSON here.

**Comment by riddell-stan** [comment]
Thanks. Glad to hear other folks are thinking about this.

Reading the notes reminded me that there's some sort of arrow/feather RPC in the works. That would be worth considering alongside protobuf and graphql.
