### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by syclik** [stan-dev/pystan#345]
#### Summary:
Match the fix for Stan's stan-dev/stan#512 which introduces logging.

#### Description:
stan-dev/stan#512 introduces a logging mechanism. Update PyStan to use a logger.

**Comment by ihincks** [comment]
Does this logging get the information that is usually printed to the terminal like "Iteration: 90 / 100 [ 90%]  (Sampling) (Chain 0)"? If so, I would be grateful to see an example.

**Comment by ariddell** [comment]
Yes, Stan sends those messages to PyStan via the interface. stderr/stdout is no longer used.

**Comment by ihincks** [comment]
Thanks. I am struggling to figure out how this works and can't find any examples. I am trying the following, but nothing is printing and `printer.count` remains at 0. I am running the latest dev branch.

```
import logging

class Printer(object):
    def __init__(self):
        self.count = 0
        
    def write(self, s):
        print s
        self.count +=1
        
    def flush(self):
        pass

printer = Printer()

ps.logger.addHandler(printer)
ps.logger.setLevel(level=logging.DEBUG)

x = model_dp.sampling(data=data, iter=100, chains=1, verbose=True)

print printer.count
```

**Comment by ariddell** [comment]
Yes, this is confusing. I think right now stderr and stdout are being
used, bypassing the logging facilities. This will/has changed going
forward. If you want to dig into this, most of the action is in
stan_fit.hpp.

I might recommend you not spend much time on this since it will all
change very soon. stan_fit.hpp is on its way out.
