### ISSUE TITLE
Printing fit summaries can take a very long time

### ISSUE THREAD

**Issue by tortarantola** [stan-dev/pystan#357]
#### Summary:
Printing a fit object in Pystan can be very slow, especially with lots of generated quantities. About 50,000 lines can take over an hour for a model that samples in 20 minutes. Is there a way to make printing more efficient, or perhaps limit it to parameters?

```
fit = model_code_obj.sampling(data=model_data, iter=2000, chains=4)
print(fit)
```

**Comment by ariddell** [comment]
Thanks for the report. This is a known issue but it's good to have feedback. How many parameters are in your model?

Calculating all the statistics for the summary takes time. Python might be somewhat slower than, say, cmdstan but it shouldn't be 10x slower.

**Comment by tortarantola** [comment]
About 500 with transformations (it's hierarchical with 48 participants). Is there a way to limit the calculations just to the parameters?

**Comment by TaskeHAMANO** [comment]
Hello. Since I also faced this problem, I looked up the profile of summary.
The link to notebook is [here](https://gist.github.com/TaskeHAMANO/d9d3d350960573830972b0844085527f).

Measurement conditions are as follows.

* Linear first order state space model.
* Let Markov chain length be 5000 (5000 + 3 parameters)
* Investigated after compiling with the profile on the cython side enabled (added `# cython: profile = True` to header)

This problem sometimes has been issued like #90, #75. And ariddell may have already known, the reason of this problem is in calculating effective sample size, especially in `get_kept_samples`. Also, I checked this function, but no idea has come. This function has already optimized by cython and cpp-implemented functions.

I left this report for someone who will be interested in.

**Comment by bob-carpenter** [comment]
Just a heads up that we're about to rewrite all this code to take advantage of NUTS's anti-correlated draws.  We're often getting n_eff greater than the number of iterations because of NUTS's tendency to draw from the second half of the chain it produces.  I'm not sure what this'll do to efficiency, but we'll be trying to optimize again.

The real bottleneck is that we have to carry out a fast Fourier transform for each parameter in order to calculate the autocorrelations at each lag, then walk over the lags gathering statistics.  

We should be able to share computation with the R-hat calculation when done together.

**Comment by ahartikainen** [comment]
I will close this for now.

`fit.__repr__` now shows 100 parameters by default and user can call `print(fit.stansummary(pars=...))`.

Making this all faster is still a problem and doing 50k autocorrs is going to be "slow".
