### ISSUE TITLE
Unfriendly license

### ISSUE THREAD

**Issue by maedoc** [stan-dev/pystan#382]
#### Summary:
GPL seems unjustified and prevents useful collaboration.

#### Description:
Most of scientific Python stack is business friendly, as is Stan.  Translating new science into e.g. clinic requires industrial partners, but they are allergic to GPL software.  We use Stan, SciPy, Django etc, and we developed our prototypes with PyStan but now have to adapt everything to use CmdStan so that our Stan models can be worked on with our collaborations.

Is there any possibility this will change in the near future?

**Comment by sakrejda** [comment]
I do believe PyStan is looking at moving to a non-viral license but it
helps to have more specific justification.  Can you describe what you would
like to do that is impossible with the GPL.? one of the issues we've run
into is a lot of generalities about this and few concrete examples.

**Comment by ariddell** [comment]
PyStan 2 contains a significant amount of code from RStan (e.g., stan_fit.hpp, >1,000 LOC). RStan is GPL3. This is why PyStan 3 is GPL'd.

**Comment by maedoc** [comment]
@sakrejda the university (Aix-Marseille University) I work for has a technology transfer office (SATT) that funds significant amounts of engineering work to take a research prototype and make it into a piece of software which can be licensed to support maintenance and further development.  Without these sorts of funding, our projects must get recycled in subsequent grants or suffer bit rot.  This is not a hand wavy generality: I have a contract with funding right now and will have to waste resources to remove PyStan as a dependency from our codebase. 

@ariddell it does not follow, from PyStan 2 containing GPL RStan code, that PyStan 3 must be GPL, unless you intend to continue using RStan code, in which case drawing attention to version numbers seems odd.

**Comment by maedoc** [comment]
@sakrejda in case it's not obvious, I meant to indicate that the sorts of funding I mentioned stipulate that GPL'd code is categorically unacceptable.  While I'm aware Stallman thinks GPL code can be licensed, this is not a stance our funding sources take, so here we are.

**Comment by ariddell** [comment]
@maedoc Fair enough. I don't think there's any plan to remove the RStan code from PyStan until version 3.

**Comment by ahartikainen** [comment]
Just a comment:

> This is why PyStan 3 is GPL'd.

Should this be PyStan 2?

**Comment by sakrejda** [comment]
@maedoc Thanks for sharing and I do empathize with your situation.  I've been involved in industry-funded research before and based on that experience I'd encourage researchers to consider that if open-source software makes them much more efficient it might be nice to share that fact with the funding entity and consider including licensing in the funding.  They're used to paying for things even though it's become a nice assumption to think you'll get all OS software for free.  Continued development of Stan is being funded by a variety of groups and individuals so they'd be in good company.  Plenty of OS outfits do dual-licensing and Stan has received legal advice about this from NumFocus so it's not exactly a murky issue. 

p.s.-my opinion on this particular issue is irrelevant since I deferred to the PyStan devs on this issue at the last dev mtg but I thought I'd say something about the pressure from corporate funding sources.

**Comment by ariddell** [comment]
@ahartikainen yes, fixed the typo.

**Comment by bob-carpenter** [comment]
The RStan code included in PyStan 2.x is C++ included as is, not R code translated to Python.  So as written, @arriddell is correct that he does not have the legal right to release PyStan under anything other than GPLv3.  

The dual-licensing of which @sakrejda speaks would be GPL and ISC for the relevant C++ code.  There are only a handful of copyright holders for the RStan code and their permission is necessary to release under a second license.  

Rather than do that, PyStan 3 is going to be licensed under ISC, which is pretty much like BSD or Apache.  So this issue will be resolved as part of that.

**Comment by bob-carpenter** [comment]
@maedoc --- despite the title of your issue, we're trying to be as friendly as possible with Stan.

**Comment by maedoc** [comment]
@bob-carpenter I'm an author of GPL packages so I get it (even shot ourselves in the foot with GPL) and yeah the issue title was poorly chosen.  ISC is welcome news, and thanks for the follow up info.

**Comment by RomainGeffraye** [comment]
Hi @bob-carpenter, we also have a similar issue with this license, is it possible to include the dual-licensing for the version 2 ? Or do you have any release plan for the 3 ?

**Comment by bob-carpenter** [comment]
@RomainGeffraye I'm not in charge of PyStan.  This one's up to @ariddell.

**Comment by ariddell** [comment]
PyStan 3 will be ISC. PyStan 2 is derived from GPL'd RStan code.
