### ISSUE TITLE
Generates all-zero array with Fixed_param; crashes with iter=1

### ISSUE THREAD

**Issue by seantalts** [stan-dev/pystan#453]
Using Fixed_param, if you use the defaults, it will seemingly generate all 0s. The way I have found to avoid this is to specify warmup=0.

If you do that, and specify iter=1, you get a float division exception.

See notebook: 

[Bugs.pdf](https://github.com/stan-dev/pystan/files/1908642/Bugs.pdf)

[Bugs.ipynb.zip](https://github.com/stan-dev/pystan/files/1908621/Bugs.ipynb.zip)

#### PyStan Version:
'2.16.0.0'

#### Python Version:
'2.7.10 (default, Feb  7 2017, 00:08:15) \n[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]'

#### Operating System:
Mac OS 10.12

**Comment by ahartikainen** [comment]
Hi, I have totally missed this.

The first problem (array of zeros) is a bug in sampling algo somewhere.

The rest of the problems are due to `__repr__` not defined for small samples. They do sample correctly, it is the printing that fails.

**Comment by ahartikainen** [comment]
Sorry for the spam.

@ariddell @bob-carpenter 

Is `Fixed_param` (in cpp) expecting always to have `warmup=0` sampling to first `num_samples` position?

Then we could force the `warmup=0` for `Fixed_param`.

**Comment by ahartikainen** [comment]
Ok, the bug is in PyStan.

@syclik (in slack) pointed out that `Fixed_param` has no meaning for warmup. 
That means PyStan should not use warmup either. 

We need to either:
- implicitly  prevent  warmup usage by setting warmup to 0
- keep warmup as array of 0 and offset array (that goes to fixed_param) so sampled values are extracted normally.
- explicitly prevent warmup by raising an error if users don't set it to 0. This would mean that user needs to set warmup and algorithm just because user uses `Fixed_param`.

I think the second option is the best one. That way we don't need to touch extract and other functions.
If this is chosen, how one offsets array in C++ (in `pystan/stan_fit.hpp`)?

**Comment by ahartikainen** [comment]
And still making the comment that currently  PyStan saves all the samples (they just lie in warmup region). One can get them out with `inc_warmup` and `permuted=False`.

    #code not tested but something similar will work
    fit = stan_model.sampling(algorithm='Fixed_param', warmup=1000, iter=2000, chains=1)
    samples = fit.extract(permuted=False, inc_warmup=True)[var][:2000-1000]

**Comment by ahartikainen** [comment]
Fixed by #491

Forces warmup to 0.
