### ISSUE TITLE
German locale breaks inference

### ISSUE THREAD

**Issue by agisbrec** [stan-dev/pystan#469]
#### Summary:
A locale which defines decimal numbers with coma (e.g. 0,5) result in faulty cpp code. The code runs without any errors or warnings, but the inference is meaningless.

#### Description:
After running this code with
env LANG=de_DE.UTF-8

```
from pystan import StanModel

code = """
data {
      int<lower=0> N;
      vector[N] y;
}
parameters {
    real<lower=0> theta;
}
model {
    y ~ inv_gamma(0.5 * theta, 0.5 * theta);
}
"""

sm = StanModel(model_code=code)
```

and looking into `sm.model_cppcode`
one finds this line
`lp_accum__.add(inv_gamma_log<propto__>(y, (0,5.0 * theta), (0,5.0 * theta)));`

Running the same code with
env LANG=en_GB.utf8
generates this instead
`lp_accum__.add(inv_gamma_log<propto__>(y, (0.5 * theta), (0.5 * theta)));`

#### PyStan Version:
The bug occurred after upgrading from 2.17.0 to 2.17.1

#### Python Version:
Python 3.6.5

#### Operating System:
Ubuntu 16.04.4 LTS

**Comment by ahartikainen** [comment]
This bug is probably in Stan / Stan-math codebase. I'm not sure if python can do anything for it.

Does the same happen with CmdStan?

cc @bob-carpenter

**Comment by bob-carpenter** [comment]
Thanks for reporting, https://github.com/agisbrec.

This is related to this longstanding Stan issue:

https://github.com/stan-dev/stan/issues/1690

@mitzimorris seems to have tracked the issue down to Boost lexical cast.  But I'm not sure if the issue is static or dynamic?  When does this environment variable get set to cause the problem?  Before the PyStan is compiled, before a model is compiled, or dynamically?

I upped the priority of that issue, but I'm pretty sure this one can be closed, or at least closed when the  Stan issue above is resolved.
