### ISSUE TITLE
How are mean, std and quantiles calculated?

### ISSUE THREAD

**Issue by s144117** [stan-dev/pystan#615]
Hi,

I was wondering how the statistics in summary are calculated.
There is very nice documentation on MCSE, n_eff, Rhat and E-BFMI, but I cannot find any on means and standard deviations.

I found a reference to the code in a comment [here](https://github.com/stan-dev/pystan/issues/396#issuecomment-343447596).
Although I have tried I cannot follow the code or find where the actual calculation occurs.

If I have 4 chains and 1000 samples is n_eff then used to extract the amount of independent samples from which the mean is calculated?
And if the mean is calculated for each chain is it then combined  mu=sqrt{mu_1 + mu_2 + mu_3 + mu_4}? Or does the between chain variance also have some influence here?
If n_eff=500 I assume every second sample is used. But what about n_eff>1000?

Thanks in advance!

**Comment by ahartikainen** [comment]
https://github.com/stan-dev/pystan/blob/develop/pystan/misc.py#L377

```
    msdfun = lambda chain: (np.mean(chain), np.std(chain, ddof=1))
    qfun = lambda chain: mquantiles(chain, probs)
    c_msd = np.array([msdfun(s) for s in ss]).flatten()
    c_quan = np.array([qfun(s) for s in ss]).flatten()
    ass = np.asarray(ss).flatten()
    msd = np.asarray(msdfun(ass))
    quan = qfun(np.asarray(ass))
```

Which means that `stansummary` mean, sd and quantile values are calculated from all the samples.

1) no
2) no
3) no subsampling done

Currently the updated mcse, ess (n_eff) and rhat can be found in ArviZ package https://github.com/arviz-devs/arviz (and are updated to PyStan at some point)

@avehtari do you have any opinion for mean, sd or quantile calculations?

**Comment by bob-carpenter** [comment]
> On Jun 24, 2019, at 2:45 AM, s144117 <notifications@github.com> wrote:
> 
> Hi,
> 
> I was wondering how the statistics in summary are calculated.
> There is very nice documentation on MCSE, n_eff, Rhat and E-BFMI, but I cannot find any on means and standard deviations.
> 
> I found a reference to the code in a comment here.

We've been thinking about providing some rank+median-based statistics
as well as means:

https://arxiv.org/abs/1903.08008

> Although I have tried I cannot follow the code or find where the actual calculation occurs.
> 
> If I have 4 chains and 1000 samples is n_eff then used to extract the amount of independent samples from which the mean is calculated?

The posterior mean is just the sample mean of the posterior draws.
It's not weighted by chain.  


> And if the mean is calculated for each chain is it then combined mu=sqrt{mu_1 + mu_2 + mu_3 + mu_4}?

It's not as we do things in Stan.

We've been thinking more about how to combine ragged chains.  That is, if
we set 500 chains to run for 10 minutes each, we'll get varying numbers
of draws per chain and varying effective sample size (ESS aka n_eff) 
if we evaluate the chain's independently. 

The big question is whether we can compensate for low ESS chains somehow
or if they're always going to introduce some bias on our expectation estimates.


> Or does the between chain variance also have some influence here?

It has an influence on R-hat, one component of which is between-chain
variance (another being within-chain variance).

As we calculate things in CmdStan (I'm pretty sure PyStan does the same),
we use mean and variance estimates from all chains together to calculate 
effective sample size.  This leads to a more conservative estimate than
if you estimate each chain's ESS individually for the same reason that if you use
the sample mean to calculate variance, you get a low bias and have to
divide by (N - 1) rather than N to correct.  Stan's new ESS calculations
also handle anticorrelated draws where you get an ESS
to note that we also deal with antithetical sampling, so that ESS can
be greater than the number of draws.  This is common with simple models.
The exact formula's described in the Stan reference manual and in the
new R-hat paper.


> If n_eff=500 I assume every second sample is used. But what about n_eff>1000?

No, that's not how it works.  We use all the draws.  The effective sample
size then provides stochastic error bounds on our expectation estimates.
The MCMC std error for a parameter is it's posterior standard deviation divided 
by sqrt(ESS) for that parameter.

**Comment by s144117** [comment]
@bob-carpenter, thank you for the in-depth answer.

> We've been thinking more about how to combine ragged chains. That is, if we set 500 chains to run for 10 minutes each, we'll get varying numbers of draws per chain and varying effective sample size (ESS aka n_eff) if we evaluate the chain's independently. The big question is whether we can compensate for low ESS chains somehow or if they're always going to introduce some bias on our expectation estimates.

Just to follow. In this case all 500 chains would have to go through a warm-up period or get passed initial state, mass matrix and step-size, right?

> As we calculate things in CmdStan (I'm pretty sure PyStan does the same), we use mean and variance estimates from all chains together to calculate effective sample size. This leads to a more conservative estimate than if you estimate each chain's ESS individually for the same reason that if you use the sample mean to calculate variance, you get a low bias and have to divide by (N - 1) rather than N to correct. Stan's new ESS calculations also handle anticorrelated draws where you get an ESS to note that we also deal with antithetical sampling, so that ESS can be greater than the number of draws. This is common with simple models. The exact formula's described in the Stan reference manual and in the new R-hat paper.

From the paper you linked I understand that the purpose is to avoid negative correlation "...by summing over pairs starting from lag t=0, the paired autocorrelation is guaranteed to be positive,..." (Apendix A). Wouldn't that mean that the ESS cannot be larger than the number of samples.

**Comment by bob-carpenter** [comment]
...

> Just to follow. In this case all 500 chains would have to go through a warm-up period or get passed initial state, mass matrix and step-size, right?

Right.

...

> rom the paper you linked I understand that the purpose is to avoid negative correlation "...by summing over pairs starting from lag t=0, the paired autocorrelation is guaranteed to be positive,..." (Apendix A). Wouldn't that mean that the ESS cannot be larger than the number of samples.

We don't avoid negative correlation.  So the ESS can be larger than the number of iterations.  We used to cap it in the interfaces so it only reported number of iterations max, but we've since found the basic formula to be calibrated when measured against actual square error.

**Comment by s144117** [comment]
I believe I understand now, thank you.
Appendix A is very similar to the 15.4 (Effective Sample Size) in the Stan Reference Manual, but the wording is slightly different . After reading it a bit more carefully I believe I got the point.

**Comment by bob-carpenter** [comment]
It's difficult to track as the doc's minimal, it all changed very recently, and it may change again if we find better estimators.
